spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:library;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;
    data: classpath:/sql/*.sql
    sql-script-encoding: UTF-8
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    properties.hibernate.globally_quoted_identifiers: true
    show-sql: true
    open-in-view: false
  # Jackson (JSON Rendering)
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
      indent-output: false
    deserialization.fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE
    mapper.accept-case-insensitive-enums: true